### ISSUE TITLE
Try JB Space

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/KMMBridge#102]
Set up a private space instance and configure a test project to publish to it.

We'll need a way to push to it from CI, of course, and also need to understand how to configure auth to access it from a client. It will need to work similarly to how github auth works (~/.netrc file).

Ideally we can do this with the free version.

https://www.jetbrains.com/space/buy/?billing=yearly#cloud

Also, I'd like the test project to live in the touchlab github org and be private, so we can hopefully set up a remote workflow to call it and run it.

**Comment by samhill303** [comment]
Can reference https://teamprivate.touchlab.dev/docs/team-docs/deep-dive/publishing-artifacts#jetbrains-space
but the config will be in netrc
