### ISSUE TITLE
Consider making artifact and version managers optional

### ISSUE THREAD

**Issue by kirillzh** [touchlab/KMMBridge#113]
I have an iOS app with bunch of Swift packages and a bunch of KMM modules. I want the iOS Swift packages to be able to pull any KMM module as a Swift package. I am using `spm` configuration for this:
```kotlin
kmmbridge {
  spm()
}
```

However this throws with:
```kotlin
You must apply an artifact manager! Call `artifactManager.set(...)` or a configuration function like `githubRelease()` in your `kmmbridge {}` block.
```

The plugin seems to require artifact and version managers even though I have no use for them. Is there any reason why we would not want to make them optional for a use case like mine?

Meanwhile adding github managers seems to work, though I am not use them:
```kotlin
kmmbridge {
  spm()
   githubReleaseVersions()
   githubReleaseArtifacts()
}
```

**Comment by russhwolf** [comment]
The intended use of the plugin is for managing published binaries. If you're not doing that, all you're really getting is package file generation. I'm going to close this for now but we're doing some thinking about local SPM development flow that might address the root need in the future.
