### ISSUE TITLE
If package written but publish fails, the versioning is stuck

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/KMMBridge#117]
Problem:
With incremental version managers, we upload a package to maven and publish to cocopods or maven. After all that, we try to push a git tag. Since we check that git tag for what should be the next tag, if something fails before we push the tag, there will be artifacts already published and if it tries to publish them again it will fail

**Comment by samhill303** [comment]
Possible approaches:
Do validation ourselves before publishing
Put up some sort of "temp" tag that gets deleted once everything works
try to roll back things?

**Comment by russhwolf** [comment]
Fixed by publishing a temp tag that we can use to detect that we failed a publish and need to increment again
