### ISSUE TITLE
Issue setting frameworkName

### ISSUE THREAD

**Issue by joreilly** [touchlab/KMMBridge#121]
I'm trying to use KMMBridge with https://github.com/joreilly/Confetti.  The github workflow etc seems to work fine but when I try to add in XCode I'm getting the following

```
downloaded archive of binary target 'shared' does not contain expected binary artifact named 'shared'
```

I have following in `build.gradle.kts` for shared code

```
kmmbridge {
    frameworkName.set("ConfettiKit")
    githubReleaseArtifacts()
    githubReleaseVersions()
    spm()
    versionPrefix.set("0.7")
}
```

and also have following

```
        it.binaries.framework {
            baseName = "ConfettiKit"
        }
```

Should there be any additional configuration needed for this?

**Comment by joreilly** [comment]
Hmm, just noticed that `Package.Swift` (https://github.com/joreilly/Confetti/blob/main/Package.swift) still has `packageName = "shared"` ....so maybe an issue if `frameworkName` name is set/updated  (in `kmmbridge` section) after initial run of gh action?

**Comment by russhwolf** [comment]
This should get fixed by #105

**Comment by russhwolf** [comment]
Check if it works for you in version 0.3.1

**Comment by joreilly** [comment]
@russhwolf was that published yet?

**Comment by russhwolf** [comment]
Oh sorry I guess we haven't deployed it yet.

**Comment by joreilly** [comment]
np, I'll grab when it's there and try it out.  What's expectation now on how framework name should be specified?

**Comment by gobetti** [comment]
if I understand correctly, once the fix is in, it should work the way you've described in the OP: `frameworkName.set("...")`

the parameter already existed but wasn't used when writing the Package.swift file

**Comment by joreilly** [comment]
does following also need to be updated to refer to 0.3.1?

```
uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuild.yml@v0.3
```

**Comment by gobetti** [comment]
I don't think so, that's a separate repo thus it may follow different versioning

**Comment by joreilly** [comment]
That's working now, thanks!

**Comment by russhwolf** [comment]
It should also pick up `framework.baseName` if you don't do `frameworkName.set()` from the kmmbridge block.
