### ISSUE TITLE
Opt out of git commit from SpmDependencyManager?

### ISSUE THREAD

**Issue by gobetti** [touchlab/KMMBridge#129]
Hi team, would it make sense to make the `git commit` something I can opt out with SpmDependencyManager?

I'd like to manage my own workflow for adding changes, committing and pushing and I'm not sure how else to work around these lines https://github.com/touchlab/KMMBridge/blob/7acb53bcdfbc0fc8790378b07259580ab96f4f1b/kmmbridge/src/main/kotlin/dependencymanager/SpmDependencyManager.kt#L52-L54

Thank you!

**Comment by russhwolf** [comment]
Can you say more about your use-case and what you want your publish flow to be? We definitely want to understand people's needs better here.

The current setup is designed to simplify some repository management by hosting the package file in the same place as the code. The intended flow is that you kick off a publish job, the artifact manager uploads a new binary, and then the dependency manager commits the updated package file so that external consumers get pointed to the new binary. We understand this isn't necessarily how everyone wants to do things (though we think it's a nice way to get started quickly without needing a huge amount of config), but we need to hear more details about what people actually are looking for so we know what to design for.

**Comment by gobetti** [comment]
hi @russhwolf , in brief I already have a workflow that publishes my kotlin library, and I'm integrating the SPM piece of it into that.

My workflow already has the logic to compute the incremented version, commit and tag. I'd like kmmbridge to only strictly build an xcframework, upload it, and update Package.swift.

I understand how the current setup does indeed help make things faster for people wanting to test this from scratch. It did help me when testing it in isolation before feeling confident to integrate into my main workflow! But now, I just need it to do less.

**Comment by russhwolf** [comment]
Thanks! That's really helpful. Just so I fully understand, what's stopping you from removing the upload from your existing workflow and calling the `kmmBridgePublish` task there instead? Are there other things your workflow is currently doing that we can better support?

**Comment by gobetti** [comment]
yeah, there are a bunch of reasons, personally I'd put "separation of responsibilities" more broadly as the first one. On a first thought, I wouldn't expect this library to do more than the 3 things I mentioned (build xcframework, upload and edit Package.swift). It's nice that it goes beyond that, but those would ideally be opt-in imho. Making them opt-out works too, but to my initial point, I wouldn't expect to have to look into how to disable things I didn't expect this tool would do for me.

Now, being more specific, referencing this block again:
https://github.com/touchlab/KMMBridge/blob/7acb53bcdfbc0fc8790378b07259580ab96f4f1b/kmmbridge/src/main/kotlin/dependencymanager/SpmDependencyManager.kt#L52-L54

1) it stages all files. I may not want that if my workflow for whatever reason makes other changes. This could be fixed by adding just Package.swift
2) it uses a specific commit message that may not be the best especially with existing projects that already have a standard for their releases. This could be fixed by introducing a configurable parameter.
3) there are other implicit assumptions here, e.g. that I'm already in the branch that I want to commit to, that this branch has an upstream branch, that my git user name and email are set as needed, etc. These are very simple git commands that I may want to control myself so that I have all sorts of customizations available.
4) there may be additional steps I want to run after `kmmBridgePublish` that should fail the entire build and not push/tag anything, but given that always happens from inside the task, either the task would have to fit a particular position in my workflow (which may not always be possible) or require workarounds that have to carry on knowledge on how `kmmBridgePublish` works internally regarding the git commands. So it'd seem a generally cleaner solution if I could skip the whole git manipulation and control it myself, explicitly without assumed external knowledge.

I think that's about it for SpmDependencyManager specifically. I had similar issues with the available VersionManagers, but that was super easy to fix given I was able to implement the interface myself and customize the way I want. In short, I didn't want the version manager to be responsible for inferring my next release version and pushing a tag.

Thanks @russhwolf !

**Comment by russhwolf** [comment]
We don't have it well documented yet, but you can now do `spm(commitManually = true)` to suppress the git operations for SPM publishing. You're then responsible for commiting package file updates and tagging the release.

**Comment by carlosmonzon** [comment]
@russhwolf I tried the` spm(commitManually = true)` in this version 0.3.4 but it was still trying to commit changes. Am I doing anything wrong?
