### ISSUE TITLE
Test sample builds on real devices

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/KMMBridge#130]
We haven't had any KMMBridge reports of issues, but I've seen some weird issues for people with arm builds and certainly podspec configs. May be XCFramework related. We obviously do the vast majority of our testing with the simulator, so I'd just like to figure out a good way to confirm things work on device.

**Comment by russhwolf** [comment]
I verified that the integration test projects run on my ipod touch. Seems to work fine (after you set up dev team etc)
