### ISSUE TITLE
Review and update samples

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/KMMBridge#139]
The "main" samples are on older versions than the Kick Start. We should review and consolidate the samples and make sure to bump versions as we release them.

Sample projects from core docs:

* [KMMBridgeSampleKotlin](https://github.com/touchlab/KMMBridgeSampleKotlin) - Shared Kotlin code
* [KMMBridgeSampleSpm](https://github.com/touchlab/KMMBridgeSampleSpm) - Xcode example with SPM
* [KMMBridgeSampleCocoaPods](https://github.com/touchlab/KMMBridgeSampleCocoaPods) - Xcode example with CocoaPods
* [PublicPodspecs](https://github.com/touchlab/PublicPodspecs) - Public CocoaPods podspec repo

**Comment by samhill303** [comment]
We probably also want to convert sampleKotlin to use maven publishing rather than releases
