### ISSUE TITLE
Add a concurrency param to integration test workflow

### ISSUE THREAD

**Issue by russhwolf** [touchlab/KMMBridge#151]
If multiple PRs are building at the same time, our integration tests can publish multiple versions and get stuck (triggering #117). We should adjust the workflow to make sure it runs serially, similar to [KMMBridgeGithubWorkflow](https://github.com/touchlab/KMMBridgeGithubWorkflow/blob/main/.github/workflows/faktorybuildbranches.yml#L32).

Note that we don't want a dynamic key in this case. eg if we had a different key for each PR, then this would not work.

**Comment by samhill303** [comment]
Should just need to update the integration test workflow in KMMBridge

**Comment by samhill303** [comment]
To test. trigger multiple workflows at the same time and make sure the versions process correctly
