### ISSUE TITLE
0.3.2版本在git 1,8.3版本下，bulid报错

### ISSUE THREAD

**Issue by weijunfeng** [touchlab/KMMBridge#156]
使用0.3.2版本时， 在git 1,8.3版本下，bulid报错

error: Fetching tags only, you probably meant:
error:    git fetch --tags

说是在git 2.0版以上才支持 git pull --tags， git版本是公司统一配置，无法更改

**Comment by kpgalligan** [comment]
You'll need to use [TimestampVersionManager](https://touchlab.github.io/KMMBridge/general/CONFIGURATION_OVERVIEW#timestampversionmanager) or [ManualVersionManager](https://touchlab.github.io/KMMBridge/general/CONFIGURATION_OVERVIEW#manualversionmanager). According to git version history, 1.8.3 is almost 10 years old, so I don't think we're going to prioritize support for that.
