### ISSUE TITLE
Add workflow configuration to handle multiple modules

### ISSUE THREAD

**Issue by russhwolf** [touchlab/KMMBridge#167]
In an app with multiple modules, we need to be able to indicate which one we want to build. Ideally this is just a modification to the existing workflow, but if necessary it could be a new alternative workflow.

Document Usage

**Comment by samhill303** [comment]
Change was implemented in https://github.com/touchlab/KMMBridgeGithubWorkflow/pull/4

Documentation needs to be added to the website here, so bringing this back to in progress @mrf7
