### ISSUE TITLE
Disable git pull unless doing a publish

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/KMMBridge#187]
We run `git pull --tags` in gradle evaluate because we need version for publishing, but that's not great to do automatically. We should disable all of that unless we pass in some kind of CLI param, to avoid local dev doing weird things.

This is doing unnecessary work in the case where someone is just developing locally. In reality, the operations are likely only needed in CI or if someone is intentionally running kmmbridge tasks locally. We could require a gradle property to be passed in order for anything publish related (the tag pull)to happen during configuration. We should quit early if we don't see this new property

**Comment by samhill303** [comment]
No longer relevant with latest versions
