### ISSUE TITLE
Framework name changes don't properly deploy

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/KMMBridge#205]
Framework name change in the kickstart project broke SPM deployment/consumption.

https://github.com/touchlab/KMMBridgeKickStart/commit/6c89d6072a71cb5eef4eded823d16ac200a4a526

Support for framework name changes was explored previously, but may have reverted and/or not had tests applied, and does not currently work well.

We should either fix or ignore the name provided.

Also, maven publishing may have trouble with capital letters in names.

Context: https://kotlinlang.slack.com/archives/CTJB58X7X/p1675252110656299

**Comment by KatieGalvin** [comment]
check for test case that hits this
