### ISSUE TITLE
Investigate running on self-hosted runners

### ISSUE THREAD

**Issue by russhwolf** [touchlab/KMMBridge#208]
Some folks have asked about using self-hosted runners for the github action and mentioned running into issues. Naively there shouldn't be any difference, but we should give this a try internally and see if there's any changes we need to make to support it.

If you're trying this yourself and hit issues, feel free to leave details here.

**Comment by russhwolf** [comment]
That sounds reasonable @mdivkovic-speech. I definitely would want to keep `macos-12` as the default, but having the host as an optional parameter makes sense. Do you want to make a PR against KMMBridgeGithubWorkflow?

**Comment by russhwolf** [comment]
Did some testing here and I thought I had it working until I realized that github apparently limits self-hosted runners to only call reusable workflows from the same org. So I think there might actually not be anything that can be done here beyond just copying our workflow to your own repo and changing runs-on there.

I'm still going to add the parameter though because it might be useful for people who need to switch what macos version they run on.

**Comment by mdivkovic-speech** [comment]
@russhwolf sorry for the very late reply and thank you for the update! 

To summarize:

- Your workflow will support the runs-on parameter, but within Touchlab's repo it will effectively only allow switching to a different GitHub hosted runner, e.g. to control the Mac OS version
- Integrators looking to use your workflow with a self hosted runner should copy it to their repo and call that copy instead

That about right?

**Comment by russhwolf** [comment]
Yeah, that's the best solution I see at the moment. I don't love it though. Definitely open to other ideas if people have them.

**Comment by kpgalligan** [comment]
I'm going to close this for now. Future version will be a much simpler default workflow.
