### ISSUE TITLE
spm() not updating Package.swift file on Github repo

### ISSUE THREAD

**Issue by gopi-b4f** [touchlab/KMMBridge#210]
### Build.gradle.kts
kmmbridge {
    mavenPublishArtifacts()
    gitTagVersions()
    versionPrefix.set("0.2")
    spm(rootDir.path)
}
addGithubPackagesRepository()

## workflow

jobs:
  call-kmmbridge-publish:
    uses: touchlab/KMMBridgeGithubWorkflow/.github/workflows/faktorybuildbranches.yml@v0.6

## Expected result

Should update package and Package.swift file 

## Current state

It is updating the package but not updating Package.swift file after the workflow action run successfully

**Comment by russhwolf** [comment]
If you're using faktorybuildbranches.yml, the update happens a separate branch rather than your main one. It should still be tagged correctly so that Xcode can pick it up when you try to consume the new version.

If you don't want that behavior, you can switch to faktorybuild.yml instead.

**Comment by gopi-b4f** [comment]
faktorybuildbranches.yml was deleting the build branch after updating the Package.swift file that I did not notice. And then I tried faktorybuild.yml and that worked. Thanks for the solution!
