### ISSUE TITLE
Compatibility issues with Java 17 and/or Gradle 8

### ISSUE THREAD

**Issue by russhwolf** [touchlab/KMMBridge#218]
Confetti project is having issues publishing via kmmbridge after updating to AGP 8, Gradle 8, Java 17. The `kmmBridgePublish` task can't be found, despite the fact that `ENABLE_PUBLISHING` is being set.

Slack thread: https://kotlinlang.slack.com/archives/CTJB58X7X/p1681838695812099

**Comment by c0de-wizard** [comment]
I had a similar issue, but I was able to get it working using this commit `b795422fddc0bbedd1239857aa46c0d9520889c2`

[GithubAction job](https://github.com/c0de-wizard/tv-maniac/actions/runs/4788064412)

**Comment by russhwolf** [comment]
This is now resolved. The only kmmbridge issue was from passing invalid args in the workflow, which is fixed in workflow version 0.9. The remaining issues were missing configuration on the project side that I misinterpreted as library/plugin issues.
