### ISSUE TITLE
swift-tools-version update

### ISSUE THREAD

**Issue by cohen72** [touchlab/KMMBridge#221]
Would it be possible to update the `// swift-tools-version:5.3` to latest? `// swift-tools-version:5.8`? (Or later)

Also, can we you support to set minimum iOS deployment target?

```
platforms: [
    .iOS(.v13)
],
```

**Comment by TemMax** [comment]
Hi! I've made a PR with these changes. Waiting for the review: https://github.com/touchlab/KMMBridge/pull/223

**Comment by kpgalligan** [comment]
There were 2 PRs for this. We've recently merged one, but I still want to review this one as it seems more robust. To be continued...
