### ISSUE TITLE
Curl command on self-hosted runners fails for pod lib lint

### ISSUE THREAD

**Issue by tmillz** [touchlab/KMMBridge#224]
## Summary

Pod lib lint fails on self-hosted runner and locally with curl returning unknown error

## Details

(error:     - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/curl -f -L -o /var/folders/xq/_s_zr8fx7879r5bx0nqtqzsh0000gn/T/d20230811-64289-1oglcp2/file.zip https://maven.pkg.github.com/<org>/host-android/host-android/common/mock-framework-kmmbridge/1.1.5/mock-framework-kmmbridge-1.1.5.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.12.1 cocoapods-downloader/1.6.3' -H Accept: application/octet-stream)

When we copy paste the curl command and remove the space in Accept: application/octent-stream the curl command works. 

local curl details
```
~ > curl --version
curl 8.2.1 (x86_64-apple-darwin21.6.0) libcurl/8.2.1 (SecureTransport) OpenSSL/3.1.2 zlib/1.2.11 brotli/1.0.9 zstd/1.5.5 libidn2/2.3.4 libssh2/1.11.0 nghttp2/1.55.1 librtmp/2.3 OpenLDAP/2.6.6
Release-Date: 2023-07-26
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli GSS-API HSTS HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe TLS-SRP UnixSockets zstd
~ > which curl
/usr/local/opt/curl/bin/curl
```
self-hosted runner curl details
```
Run curl --version
curl 7.86.0 (x86_64-apple-darwin22.0) libcurl/7.86.0 (SecureTransport) LibreSSL/3.3.6 zlib/1.2.11 nghttp2/1.47.0
Release-Date: 2022-10-2[6](https://github.com/<org>/org-runner-experiments/actions/runs/5939753886/job/16106843037#step:3:7)
Protocols: dict file ftp ftps gopher gophers http https imap imaps ldap ldaps mqtt pop3 pop3s rtsp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS GSS-API HSTS HTTP2 HTTPS-proxy IPv6 Kerberos Largefile libz MultiSSL NTLM NTLM_WB SPNEGO SSL threadsafe UnixSockets
which curl
/usr/bin/curl
```

## Reproduction

Running slightly modified version of the factorybuildbranches.yml workflow.  We can provide details if required.

## Expected result

Expecting the curl command to work.

## Current state

Curl returns ERROR | [iOS] unknown for pod lib lint curl.

## Possible Fix

Suspect the issue has to do with this line https://github.com/touchlab/KMMBridge/blob/main/kmmbridge/src/main/kotlin/dependencymanager/CocoapodsDependencyManager.kt#L143 

Removing the space between Accept: application/octet-stream should fix the issue without impacting for other curl versions.

**Comment by TadeasKriz** [comment]
Thanks for this detailed report! We don't need to remove the space, we just need to replace the `:headers => ['Accept: application/octet-stream']` with ` :headers => ["'Accept: application/octet-stream'"]` (notice the extra quotes). I checked online, and this seems to be the way to do it correctly, because headers are passed as-is to curl. 

Could you create a pull request with this change?

Thank you!

**Comment by tmillz** [comment]
Will do, thank you for the quick follow up and providing a better fix 👍

**Comment by kpgalligan** [comment]
Merged PR. Thanks!
