### ISSUE TITLE
autoversion - fatal: '.0' is not a valid tag name

### ISSUE THREAD

**Issue by Giuliopime** [touchlab/KMMBridge#234]
## Summary
When publishing with the default GitHub Workflow I get the following error in one of the last steps:
```
Run touchlab/autoversion-finishrelease@main
Error: fatal: '.0' is not a valid tag name.
```
The publishing though goes trough fine and it appears correctly on GitHub, can I simply ignore this error?

My repo is open source here https://github.com/Giuliopime/ZenBreak

**Comment by kpgalligan** [comment]
This is a few months old, so not sure if it's a problem still. Autoversion needs to be correctly configured if you plan to do auto version numbering, so I would guess there are associated issues with tags and SPM versions as a result. We have an updated version coming out without any autoversion. It has added more complexity than it was work, in retrospect.
