### ISSUE TITLE
Android artefacts are always published with 1.0.0 version 

### ISSUE THREAD

**Issue by VitaSokolova** [touchlab/KMMBridge#238]
## Summary

Hi! I created a test KMP [project](https://github.com/VitaSokolova/KMP-shared) and I used [KMMBridgeSKIETemplate](https://github.com/touchlab/KMMBridgeSKIETemplate) template, but I ran into issue that I need to perform extra actions before publishing (like inject GitHub secrets into local.properties), that's why I copied `faktorybuildautoversion.yml` into my project. Unfortunately, despite 0 changes I've made yet, my Android library is always published with version 1.0.0. Could you please help me to investigate the reasons? 

## Details
[Repository](https://github.com/VitaSokolova/KMP-shared)
[Packages](https://github.com/VitaSokolova?tab=packages&repo_name=KMP-shared)
[Actions](https://github.com/VitaSokolova/KMP-shared/actions)

## Reproduction

Check the packages and actions

## Expected result

`All-publish.yml` workflow autoincrements and publishes an android library with a new version after every run. 

## Current state

The packages are rewritten and always have 1.0.0 version. 

## Possible Fix

I wish I knew.

**Comment by PiotrPrus** [comment]
Hi Vita, I had the same issue, and spotted that in `build.gradle`(shared) I has a line that set a version to 1.0.0. I used it because the multiplatformSwiftPackage library was requiring it in the past. When I removed it the autover from kmmbridge is working now.
Basically check your code for any hardcoded version :) good luck

**Comment by hanrw** [comment]
Just check all the build.gradle.kt and DO NOT use hardcoded version there.
example config
```kotlin
val autoVersion = project.property(
    if (project.hasProperty("AUTO_VERSION")) {
        "AUTO_VERSION"
    } else {
        "LIBRARY_VERSION"
    }
) as String

subprojects {
    val GROUP: String by project
    group = GROUP
    version = autoVersion
}
```
