### ISSUE TITLE
spm with latest version(1.0.1) generated Package.swift looks not correct

### ISSUE THREAD

**Issue by hanrw** [touchlab/KMMBridge#258]
by given:  
```kotlin
 spm(swiftToolVersion = "5.9") {
        iOS { v("14") }
        macOS { v("13") }
    }
```

expect:
```kotlin
// swift-tools-version:5.9
import PackageDescription

let packageName = "shared"

let package = Package(
    name: packageName,
    platforms: [
         .iOS(.v14),
         .macOS(.v13)
    ],
    products: [
        .library(
            name: packageName,
            targets: [packageName]
        ),
    ],
    targets: [
        .binaryTarget(
            name: packageName,
            path: "./shared/build/XCFrameworks/debug/\(packageName).xcframework"
        )
        ,
    ]
)
```

but generated
```kotlin
// swift-tools-version:5.9
import PackageDescription

let packageName = "shared"

let package = Package(
    name: packageName,
    platforms: [
         .macOS(.v13)
    ],
    products: [
        .library(
            name: packageName,
            targets: [packageName]
        ),
    ],
    targets: [
        .binaryTarget(
            name: packageName,
            path: "./shared/build/XCFrameworks/debug/\(packageName).xcframework"
        )
        ,
    ]
)
```

**Comment by kpgalligan** [comment]
The logic that builds the `Package.swift` file checks the apple platforms you've defined for spm against the Kotlin target architectures you've defined. If you have an spm platform definition, but your build isn't actually building for that platform, it isn't written to your `Package.swift` file.

For example, if your Kotlin gradle config looks like this:

```kotlin
kotlin {
    listOf(
        iosX64(),
        iosArm64(),
        iosSimulatorArm64(),
        macosArm64()
    ).forEach {
        it.binaries.framework {
            isStatic = true
        }
    }
}

kmmbridge {
    gitHubReleaseArtifacts()
    spm(swiftToolVersion = "5.8") {
        iOS { v("14") }
        macOS { v("13") }
    }
}
```

The relevant part of the `Package.swift` file will look like this:

```swift
let package = Package(
    name: packageName,
    platforms: [
        .iOS(.v14),
        .macOS(.v13)
    ],
    products: [
// Etc
```

If you remove `macosArm64()` it'll result in this:

```swift
let package = Package(
    name: packageName,
    platforms: [
        .iOS(.v14)
    ],
    products: [
// Etc
```

It might be confusing, but not an unreasonable solution to the question of what to do in that case. The choices would be:

* Ignore it and write whatever's in the Gradle config
* Throw an error and fail the build
* Filter declared spm targets against the Kotlin architecture targets that are actually being used (which is what it does now)

I don't have a strong feeling either way, TBH. What I don't know is if there are potential downsides for declaring a platform that your framework doesn't actually implement. I don't know if it'll cause build issues, but it is kind of odd to declare it if it isn't supported.

**Comment by hanrw** [comment]
Yes, it can be a bit confusing due to the way SPM depends on Kotlin targets. For instance, when we have a single target like iosX64, alongside iOS and macOS targets in the SPM configuration, it becomes confusing. What if SPM were independent of Kotlin targets? This way, it would always generate the same Package.swift from its configurations.

**Comment by kpgalligan** [comment]
> when we have a single target like iosX64, alongside iOS and macOS targets in the SPM configuration, it becomes confusing. 

I don't at all understand the scenario you're suggesting.

I'm going to close both this and the PR for now. This isn't a bug. We are possibly doing some more significant updates in the near future and maybe this part will get some thought, but I'm not entirely sold on the idea that we should declare platform targets in the `Package.swift` file for platforms we aren't actually exporting. At the same time, I don't know if it's a problem either way.

I can see the argument that there's not much value to filtering the targets. Just print what's declared. However, we'll give it some thought for 1.1.

**Comment by hanrw** [comment]
thx i see your point.
