### ISSUE TITLE
KMMBridgeGithubWorkflowv1.1 using macos 12 for github actions

### ISSUE THREAD

**Issue by DominicGBauer** [touchlab/KMMBridge#262]
## Summary

I am seeing this error in github actions when using https://github.com/touchlab/KMMBridgeGithubWorkflow/
```
The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15. For more details, see https://github.com/actions/runner-images/issues/10721
```

## Details

It looks like the yaml file was upgraded to use `macos-latest` but a new version has not been released. I see that the `KMMBridgeGithubWorkflow` repo has been archived so is there a new way that I missed to accomplish the same goal?

## Reproduction
https://github.com/powersync-ja/powersync-kotlin/actions/runs/11665777241/job/32482030518

**Comment by kpgalligan** [comment]
A new version has been published: [v1.2](https://github.com/touchlab/KMMBridgeGithubWorkflow/releases/tag/v1.2)
