### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by kpgalligan** [touchlab/KMMBridge#28]
* ~~Add OSS License!!!~~
* ~~Update plugin version in readme~~
* ~~Link to KMM Bridge blog post in readme (does not exist yet)~~
* ~~Link to Repo in blog posts~~
* ~~Scan github issues and git history for sensitive info~~
* ~~Make Repos public~~
  * ~~KMMBridge~~
  * ~~Samples~~
  * ~~Podspec~~
* ~~Double check that JB's post links correctly~~
  * ~~Also confirm all the other links are right such as touchlab*HQ* and touchlab.*co*~~
* ~~Publish a version of the KMM Bridge Actions workflow (not main)~~
 * ~~Change samples and docs to use version~~
* ~~Review samples~~
 * ~~Update docs~~
 * ~~Update versions (plugin, etc)~~

Add to this list as we're prepping release...

**Comment by KatieGalvin** [comment]
- blog post publish ; repository to blog and blog to repository links present and working
